"""initial normalized scheduling schema

Revision ID: b3f6901aafac
Revises: 
Create Date: 2026-09-01 11:10:38.226090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'b3f6901aafac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('mobile_number', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mobile_number')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('teams',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shift_templates',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('end_time <> start_time', name='ck_template_nonzero_duration'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_templates_team_id'), 'shift_templates', ['team_id'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'name', name='uq_skills_team_name')
    )
    op.create_index(op.f('ix_skills_team_id'), 'skills', ['team_id'], unique=False)
    op.create_table('team_invitations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('invited_email', sa.String(length=320), nullable=False),
    sa.Column('proposed_role', sa.Enum('OWNER', 'MANAGER', 'EMPLOYEE', name='invitation_role'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'EXPIRED', name='invitation_status'), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_invitations_team_status', 'team_invitations', ['team_id', 'status'], unique=False)
    op.create_table('team_members',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'MANAGER', 'EMPLOYEE', name='membership_role'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'INVITED', name='membership_status'), nullable=False),
    sa.Column('contracted_minutes_week', sa.Integer(), nullable=False),
    sa.Column('maximum_minutes_week', sa.Integer(), nullable=False),
    sa.Column('maximum_days_week', sa.SmallInteger(), nullable=False),
    sa.Column('maximum_consecutive_days', sa.SmallInteger(), nullable=False),
    sa.Column('minimum_rest_minutes', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('contracted_minutes_week >= 0', name='ck_member_contract_minutes'),
    sa.CheckConstraint('maximum_consecutive_days BETWEEN 1 AND 7', name='ck_member_consecutive_days'),
    sa.CheckConstraint('maximum_days_week BETWEEN 1 AND 7', name='ck_member_max_days'),
    sa.CheckConstraint('maximum_minutes_week >= contracted_minutes_week', name='ck_member_max_minutes'),
    sa.CheckConstraint('minimum_rest_minutes >= 0', name='ck_member_rest_minutes'),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name='ck_member_effective_period'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'user_id', name='uq_team_members_team_user')
    )
    op.create_index(op.f('ix_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_members_user_id'), 'team_members', ['user_id'], unique=False)
    op.create_table('team_policies',
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('solver_limit_seconds', sa.Integer(), nullable=False),
    sa.Column('fairness_weight', sa.Integer(), nullable=False),
    sa.Column('preference_weight', sa.Integer(), nullable=False),
    sa.Column('overtime_weight', sa.Integer(), nullable=False),
    sa.Column('change_weight', sa.Integer(), nullable=False),
    sa.Column('max_hours_hard', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('solver_limit_seconds BETWEEN 1 AND 300', name='ck_policy_solver_limit'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('member_skills',
    sa.Column('team_member_id', sa.BigInteger(), nullable=False),
    sa.Column('skill_id', sa.BigInteger(), nullable=False),
    sa.Column('proficiency', sa.Enum('QUALIFIED', 'ADVANCED', name='skill_proficiency'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_member_id'], ['team_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_member_id', 'skill_id')
    )
    op.create_table('rosters',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='roster_status'), nullable=False),
    sa.Column('solver_status', sa.Enum('PENDING', 'RUNNING', 'FEASIBLE', 'OPTIMAL', 'INFEASIBLE', 'FAILED', name='solver_status'), nullable=False),
    sa.Column('solver_duration_ms', sa.Integer(), nullable=True),
    sa.Column('objective_score', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('solver_metadata', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('created_by_member_id', sa.BigInteger(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('period_end >= period_start', name='ck_roster_period'),
    sa.ForeignKeyConstraint(['created_by_member_id'], ['team_members.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rosters_team_period', 'rosters', ['team_id', 'period_start', 'period_end'], unique=False)
    op.create_index(
        'uq_rosters_published_period',
        'rosters',
        ['team_id', 'period_start', 'period_end'],
        unique=True,
        postgresql_where=sa.text("status = 'PUBLISHED'"),
        sqlite_where=sa.text("status = 'PUBLISHED'"),
    )
    op.create_table('shift_instances',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('template_id', sa.BigInteger(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('required_staff', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CANCELLED', 'COMPLETED', name='shift_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('ends_at > starts_at', name='ck_shift_instance_duration'),
    sa.CheckConstraint('required_staff > 0', name='ck_shift_instance_staff'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['shift_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shift_instances_team_starts', 'shift_instances', ['team_id', 'starts_at'], unique=False)
    op.create_table('shift_template_rules',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('shift_template_id', sa.BigInteger(), nullable=False),
    sa.Column('weekday', sa.SmallInteger(), nullable=False),
    sa.Column('required_staff', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.CheckConstraint('required_staff > 0', name='ck_template_rule_staff'),
    sa.CheckConstraint('weekday BETWEEN 0 AND 6', name='ck_template_rule_weekday'),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name='ck_template_rule_effective_period'),
    sa.ForeignKeyConstraint(['shift_template_id'], ['shift_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shift_template_id', 'weekday', 'effective_from', name='uq_template_rule_period')
    )
    op.create_index(op.f('ix_shift_template_rules_shift_template_id'), 'shift_template_rules', ['shift_template_id'], unique=False)
    op.create_table('shift_template_skills',
    sa.Column('shift_template_id', sa.BigInteger(), nullable=False),
    sa.Column('skill_id', sa.BigInteger(), nullable=False),
    sa.Column('required_count', sa.Integer(), nullable=False),
    sa.CheckConstraint('required_count > 0', name='ck_template_skill_count'),
    sa.ForeignKeyConstraint(['shift_template_id'], ['shift_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('shift_template_id', 'skill_id')
    )
    op.create_table('assignments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('roster_id', sa.BigInteger(), nullable=False),
    sa.Column('shift_instance_id', sa.BigInteger(), nullable=False),
    sa.Column('team_member_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.Enum('SOLVER', 'MANUAL', 'OVERRIDE', name='assignment_source'), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['roster_id'], ['rosters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_instance_id'], ['shift_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_member_id'], ['team_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roster_id', 'shift_instance_id', 'team_member_id', name='uq_assignment_member_shift')
    )
    op.create_index('ix_assignments_roster_shift', 'assignments', ['roster_id', 'shift_instance_id'], unique=False)
    op.create_table('shift_instance_skills',
    sa.Column('shift_instance_id', sa.BigInteger(), nullable=False),
    sa.Column('skill_id', sa.BigInteger(), nullable=False),
    sa.Column('required_count', sa.Integer(), nullable=False),
    sa.CheckConstraint('required_count > 0', name='ck_instance_skill_count'),
    sa.ForeignKeyConstraint(['shift_instance_id'], ['shift_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('shift_instance_id', 'skill_id')
    )
    op.create_table('time_requests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('team_member_id', sa.BigInteger(), nullable=False),
    sa.Column('shift_instance_id', sa.BigInteger(), nullable=True),
    sa.Column('request_type', sa.Enum('UNAVAILABLE', 'HOLIDAY', 'SICK_LEAVE', 'PERSONAL_LEAVE', 'PREFERRED_SHIFT', 'AVOID_SHIFT', name='time_request_type'), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='request_status'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by_member_id', sa.BigInteger(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('ends_at > starts_at', name='ck_time_request_duration'),
    sa.ForeignKeyConstraint(['reviewed_by_member_id'], ['team_members.id'], ),
    sa.ForeignKeyConstraint(['shift_instance_id'], ['shift_instances.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_member_id'], ['team_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_time_requests_member_period', 'time_requests', ['team_member_id', 'starts_at', 'ends_at'], unique=False)
    op.create_index(op.f('ix_time_requests_team_member_id'), 'time_requests', ['team_member_id'], unique=False)
    op.create_table('assignment_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('assignment_id', sa.BigInteger(), nullable=False),
    sa.Column('actor_member_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.Enum('CREATED', 'LOCKED', 'UNLOCKED', 'REASSIGNED', 'REMOVED', name='assignment_event_type'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('previous_values', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('new_values', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_member_id'], ['team_members.id'], ),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignment_events_assignment_id'), 'assignment_events', ['assignment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assignment_events_assignment_id'), table_name='assignment_events')
    op.drop_table('assignment_events')
    op.drop_index(op.f('ix_time_requests_team_member_id'), table_name='time_requests')
    op.drop_index('ix_time_requests_member_period', table_name='time_requests')
    op.drop_table('time_requests')
    op.drop_table('shift_instance_skills')
    op.drop_index('ix_assignments_roster_shift', table_name='assignments')
    op.drop_table('assignments')
    op.drop_table('shift_template_skills')
    op.drop_index(op.f('ix_shift_template_rules_shift_template_id'), table_name='shift_template_rules')
    op.drop_table('shift_template_rules')
    op.drop_index('ix_shift_instances_team_starts', table_name='shift_instances')
    op.drop_table('shift_instances')
    op.drop_index('ix_rosters_team_period', table_name='rosters')
    op.drop_index('uq_rosters_published_period', table_name='rosters')
    op.drop_table('rosters')
    op.drop_table('member_skills')
    op.drop_table('team_policies')
    op.drop_index(op.f('ix_team_members_user_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_team_id'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index('ix_invitations_team_status', table_name='team_invitations')
    op.drop_table('team_invitations')
    op.drop_index(op.f('ix_skills_team_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_shift_templates_team_id'), table_name='shift_templates')
    op.drop_table('shift_templates')
    op.drop_table('teams')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
