"""enforce one pending invitation per email

Revision ID: f88f4b58d0d6
Revises: b3f6901aafac
Create Date: 2026-09-01 11:29:38.999589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f88f4b58d0d6'
down_revision: Union[str, None] = 'b3f6901aafac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_invitations_pending_email', 'team_invitations', ['team_id', 'invited_email'], unique=True, postgresql_where=sa.text("status = 'PENDING'"), sqlite_where=sa.text("status = 'PENDING'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_invitations_pending_email', table_name='team_invitations', postgresql_where=sa.text("status = 'PENDING'"), sqlite_where=sa.text("status = 'PENDING'"))
    # ### end Alembic commands ###
